var brand = "mala-paractica";
let counter =100;
const token ="abc123";

console.log(token);
counter =200
console.log(counter);


// comentrios demuna linea


/*
 este es un comentario
  multiline :)
*/

//interpolacion
let interpolation = `el valor del couter es ${counter}`;
console.log(interpolation);
console.log("el valor del counte es",counter);
console.log("el valor del counte es", +counter);

 const persons =[{
    "id": 1,
    "first_name": "Morganica",
    "last_name": "Drogan",
    "email": "mdrogan0@msn.com",
    "gender": "Female",
    "ip_address": "145.189.76.102"
  }, {
    "id": 2,
    "first_name": "Sallyanne",
    "last_name": "Milkins",
    "email": "smilkins1@sfgate.com",
    "gender": "Female",
    "ip_address": "8.228.8.119"
  }, {
    "id": 3,
    "first_name": "Cassey",
    "last_name": "Tidball",
    "email": "ctidball2@pagesperso-orange.fr",
    "gender": "Female",
    "ip_address": "103.128.102.216"
  }, {
    "id": 4,
    "first_name": "Jammal",
    "last_name": "Unthank",
    "email": "junthank3@symantec.com",
    "gender": "Male",
    "ip_address": "135.17.7.236"
  }, {
    "id": 5,
    "first_name": "Hedvige",
    "last_name": "Rouzet",
    "email": "hrouzet4@reddit.com",
    "gender": "Female",
    "ip_address": "211.33.79.89"
  }, {
    "id": 6,
    "first_name": "Parker",
    "last_name": "Ratnage",
    "email": "pratnage5@ycombinator.com",
    "gender": "Male",
    "ip_address": "48.22.104.146"
  }, {
    "id": 7,
    "first_name": "Llywellyn",
    "last_name": "Kyteley",
    "email": "lkyteley6@si.edu",
    "gender": "Male",
    "ip_address": "230.237.183.70"
  }, {
    "id": 8,
    "first_name": "Eugenia",
    "last_name": "Girone",
    "email": "egirone7@sciencedirect.com",
    "gender": "Female",
    "ip_address": "234.161.67.148"
  }, {
    "id": 9,
    "first_name": "Addie",
    "last_name": "Melbourn",
    "email": "amelbourn8@apple.com",
    "gender": "Female",
    "ip_address": "227.145.85.119"
  }, {
    "id": 10,
    "first_name": "Ginelle",
    "last_name": "Staneland",
    "email": "gstaneland9@issuu.com",
    "gender": "Female",
    "ip_address": "26.26.240.214"
  }, {
    "id": 11,
    "first_name": "Dorisa",
    "last_name": "Cowlam",
    "email": "dcowlama@wikipedia.org",
    "gender": "Female",
    "ip_address": "171.155.133.70"
  }, {
    "id": 12,
    "first_name": "Bert",
    "last_name": "MacNucator",
    "email": "bmacnucatorb@jugem.jp",
    "gender": "Male",
    "ip_address": "19.31.164.135"
  }, {
    "id": 13,
    "first_name": "Karee",
    "last_name": "MacTague",
    "email": "kmactaguec@ning.com",
    "gender": "Female",
    "ip_address": "178.86.187.193"
  }, {
    "id": 14,
    "first_name": "Gav",
    "last_name": "Elsmore",
    "email": "gelsmored@tinyurl.com",
    "gender": "Male",
    "ip_address": "6.86.222.254"
  }, {
    "id": 15,
    "first_name": "Ashby",
    "last_name": "Konke",
    "email": "akonkee@amazon.de",
    "gender": "Male",
    "ip_address": "49.247.169.149"
  }, {
    "id": 16,
    "first_name": "Desmond",
    "last_name": "Radbourn",
    "email": "dradbournf@sciencedirect.com",
    "gender": "Male",
    "ip_address": "0.227.138.71"
  }, {
    "id": 17,
    "first_name": "Millie",
    "last_name": "Llorente",
    "email": "mllorenteg@barnesandnoble.com",
    "gender": "Genderqueer",
    "ip_address": "89.45.226.194"
  }, {
    "id": 18,
    "first_name": "Lenard",
    "last_name": "Drinkale",
    "email": "ldrinkaleh@ca.gov",
    "gender": "Male",
    "ip_address": "48.66.152.176"
  }, {
    "id": 19,
    "first_name": "Antoine",
    "last_name": "Ackred",
    "email": "aackredi@ehow.com",
    "gender": "Male",
    "ip_address": "225.136.51.109"
  }, {
    "id": 20,
    "first_name": "Brigg",
    "last_name": "Blackham",
    "email": "bblackhamj@example.com",
    "gender": "Male",
    "ip_address": "34.130.224.151"
  }, {
    "id": 21,
    "first_name": "Ossie",
    "last_name": "Isted",
    "email": "oistedk@newsvine.com",
    "gender": "Male",
    "ip_address": "126.164.71.219"
  }, {
    "id": 22,
    "first_name": "Lawton",
    "last_name": "Bever",
    "email": "lbeverl@cocolog-nifty.com",
    "gender": "Male",
    "ip_address": "30.126.37.246"
  }, {
    "id": 23,
    "first_name": "Konstantin",
    "last_name": "Prop",
    "email": "kpropm@ucla.edu",
    "gender": "Male",
    "ip_address": "200.192.64.114"
  }, {
    "id": 24,
    "first_name": "Bert",
    "last_name": "Hradsky",
    "email": "bhradskyn@phpbb.com",
    "gender": "Female",
    "ip_address": "136.222.108.227"
  }, {
    "id": 25,
    "first_name": "Elliot",
    "last_name": "Ayrton",
    "email": "eayrtono@51.la",
    "gender": "Male",
    "ip_address": "96.229.71.82"
  }, {
    "id": 26,
    "first_name": "Lorri",
    "last_name": "Ickovici",
    "email": "lickovicip@etsy.com",
    "gender": "Female",
    "ip_address": "224.161.87.92"
  }, {
    "id": 27,
    "first_name": "Marcela",
    "last_name": "Gleder",
    "email": "mglederq@g.co",
    "gender": "Female",
    "ip_address": "21.250.130.184"
  }, {
    "id": 28,
    "first_name": "Christie",
    "last_name": "Najera",
    "email": "cnajerar@google.co.jp",
    "gender": "Male",
    "ip_address": "8.143.38.81"
  }, {
    "id": 29,
    "first_name": "Matthiew",
    "last_name": "Bradnocke",
    "email": "mbradnockes@ucla.edu",
    "gender": "Male",
    "ip_address": "242.16.253.132"
  }, {
    "id": 30,
    "first_name": "Barn",
    "last_name": "Iorizzi",
    "email": "biorizzit@issuu.com",
    "gender": "Male",
    "ip_address": "13.97.139.254"
  }, {
    "id": 31,
    "first_name": "Shea",
    "last_name": "Tremoulet",
    "email": "stremouletu@apache.org",
    "gender": "Male",
    "ip_address": "153.196.55.188"
  }, {
    "id": 32,
    "first_name": "Nelle",
    "last_name": "Calan",
    "email": "ncalanv@usa.gov",
    "gender": "Female",
    "ip_address": "146.0.208.76"
  }, {
    "id": 33,
    "first_name": "Brigitte",
    "last_name": "Domegan",
    "email": "bdomeganw@bizjournals.com",
    "gender": "Female",
    "ip_address": "231.97.220.193"
  }, {
    "id": 34,
    "first_name": "Carmina",
    "last_name": "Manuello",
    "email": "cmanuellox@rakuten.co.jp",
    "gender": "Female",
    "ip_address": "83.91.38.77"
  }, {
    "id": 35,
    "first_name": "Lucretia",
    "last_name": "Gilpin",
    "email": "lgilpiny@msn.com",
    "gender": "Female",
    "ip_address": "100.189.9.22"
  }, {
    "id": 36,
    "first_name": "Clarita",
    "last_name": "Fossett",
    "email": "cfossettz@yolasite.com",
    "gender": "Bigender",
    "ip_address": "85.102.246.51"
  }, {
    "id": 37,
    "first_name": "Elga",
    "last_name": "Batecok",
    "email": "ebatecok10@g.co",
    "gender": "Female",
    "ip_address": "6.114.119.218"
  }, {
    "id": 38,
    "first_name": "Byrann",
    "last_name": "Martijn",
    "email": "bmartijn11@prlog.org",
    "gender": "Male",
    "ip_address": "1.64.74.169"
  }, {
    "id": 39,
    "first_name": "Kendre",
    "last_name": "Clayworth",
    "email": "kclayworth12@hubpages.com",
    "gender": "Agender",
    "ip_address": "129.174.111.28"
  }, {
    "id": 40,
    "first_name": "Nady",
    "last_name": "MacWhirter",
    "email": "nmacwhirter13@unicef.org",
    "gender": "Female",
    "ip_address": "112.252.219.174"
  }, {
    "id": 41,
    "first_name": "Abdul",
    "last_name": "Dumbelton",
    "email": "adumbelton14@4shared.com",
    "gender": "Male",
    "ip_address": "249.22.208.224"
  }, {
    "id": 42,
    "first_name": "Aksel",
    "last_name": "Connor",
    "email": "aconnor15@hao123.com",
    "gender": "Male",
    "ip_address": "61.212.197.192"
  }, {
    "id": 43,
    "first_name": "Ase",
    "last_name": "Wickrath",
    "email": "awickrath16@cmu.edu",
    "gender": "Male",
    "ip_address": "27.12.87.117"
  }, {
    "id": 44,
    "first_name": "Kayle",
    "last_name": "Totaro",
    "email": "ktotaro17@apple.com",
    "gender": "Female",
    "ip_address": "17.211.148.68"
  }, {
    "id": 45,
    "first_name": "Pam",
    "last_name": "Kilty",
    "email": "pkilty18@cnbc.com",
    "gender": "Female",
    "ip_address": "62.50.160.220"
  }, {
    "id": 46,
    "first_name": "Hope",
    "last_name": "Henden",
    "email": "hhenden19@eventbrite.com",
    "gender": "Bigender",
    "ip_address": "171.157.20.134"
  }, {
    "id": 47,
    "first_name": "Ezekiel",
    "last_name": "Lillo",
    "email": "elillo1a@skyrock.com",
    "gender": "Male",
    "ip_address": "78.203.108.140"
  }, {
    "id": 48,
    "first_name": "Nissy",
    "last_name": "Spileman",
    "email": "nspileman1b@yandex.ru",
    "gender": "Female",
    "ip_address": "255.233.244.217"
  }, {
    "id": 49,
    "first_name": "Kelby",
    "last_name": "Ogbourne",
    "email": "kogbourne1c@mashable.com",
    "gender": "Genderqueer",
    "ip_address": "155.97.48.163"
  }, {
    "id": 50,
    "first_name": "Stanton",
    "last_name": "Waldocke",
    "email": "swaldocke1d@ox.ac.uk",
    "gender": "Male",
    "ip_address": "49.151.19.160"
  }, {
    "id": 51,
    "first_name": "Amalia",
    "last_name": "Minnock",
    "email": "aminnock1e@themeforest.net",
    "gender": "Female",
    "ip_address": "49.65.88.61"
  }, {
    "id": 52,
    "first_name": "Issy",
    "last_name": "Meader",
    "email": "imeader1f@google.de",
    "gender": "Female",
    "ip_address": "85.238.219.131"
  }, {
    "id": 53,
    "first_name": "Kennan",
    "last_name": "Burburough",
    "email": "kburburough1g@studiopress.com",
    "gender": "Agender",
    "ip_address": "10.113.117.21"
  }, {
    "id": 54,
    "first_name": "Barbra",
    "last_name": "Ledgeway",
    "email": "bledgeway1h@chicagotribune.com",
    "gender": "Genderqueer",
    "ip_address": "141.77.26.203"
  }, {
    "id": 55,
    "first_name": "Barney",
    "last_name": "Kelshaw",
    "email": "bkelshaw1i@cisco.com",
    "gender": "Male",
    "ip_address": "186.84.99.24"
  }, {
    "id": 56,
    "first_name": "Juanita",
    "last_name": "Gallifont",
    "email": "jgallifont1j@qq.com",
    "gender": "Bigender",
    "ip_address": "169.224.131.21"
  }, {
    "id": 57,
    "first_name": "Torey",
    "last_name": "MacCallester",
    "email": "tmaccallester1k@imdb.com",
    "gender": "Male",
    "ip_address": "17.191.80.236"
  }, {
    "id": 58,
    "first_name": "Jyoti",
    "last_name": "Curman",
    "email": "jcurman1l@ycombinator.com",
    "gender": "Polygender",
    "ip_address": "5.251.191.98"
  }, {
    "id": 59,
    "first_name": "Darcee",
    "last_name": "Barizeret",
    "email": "dbarizeret1m@wiley.com",
    "gender": "Female",
    "ip_address": "84.90.226.198"
  }, {
    "id": 60,
    "first_name": "Artus",
    "last_name": "Pristnor",
    "email": "apristnor1n@amazon.de",
    "gender": "Male",
    "ip_address": "251.55.144.34"
  }, {
    "id": 61,
    "first_name": "Minette",
    "last_name": "Malpas",
    "email": "mmalpas1o@hibu.com",
    "gender": "Female",
    "ip_address": "196.254.175.67"
  }, {
    "id": 62,
    "first_name": "Alma",
    "last_name": "Flute",
    "email": "aflute1p@discovery.com",
    "gender": "Female",
    "ip_address": "26.61.105.97"
  }, {
    "id": 63,
    "first_name": "Norton",
    "last_name": "Ginie",
    "email": "nginie1q@about.me",
    "gender": "Male",
    "ip_address": "54.204.201.204"
  }, {
    "id": 64,
    "first_name": "Terrye",
    "last_name": "Berntsson",
    "email": "tberntsson1r@ehow.com",
    "gender": "Female",
    "ip_address": "11.68.154.238"
  }, {
    "id": 65,
    "first_name": "Jarvis",
    "last_name": "Turnpenny",
    "email": "jturnpenny1s@rambler.ru",
    "gender": "Male",
    "ip_address": "77.40.245.183"
  }, {
    "id": 66,
    "first_name": "Luz",
    "last_name": "Amey",
    "email": "lamey1t@myspace.com",
    "gender": "Female",
    "ip_address": "148.101.185.99"
  }, {
    "id": 67,
    "first_name": "Dolf",
    "last_name": "Eastridge",
    "email": "deastridge1u@census.gov",
    "gender": "Male",
    "ip_address": "10.214.65.178"
  }, {
    "id": 68,
    "first_name": "Bearnard",
    "last_name": "Meyer",
    "email": "bmeyer1v@gnu.org",
    "gender": "Male",
    "ip_address": "61.108.1.139"
  }, {
    "id": 69,
    "first_name": "Cahra",
    "last_name": "Breitler",
    "email": "cbreitler1w@mail.ru",
    "gender": "Polygender",
    "ip_address": "5.230.162.194"
  }, {
    "id": 70,
    "first_name": "Mathian",
    "last_name": "Saulter",
    "email": "msaulter1x@cbslocal.com",
    "gender": "Male",
    "ip_address": "199.207.177.245"
  }, {
    "id": 71,
    "first_name": "Waldemar",
    "last_name": "McVeigh",
    "email": "wmcveigh1y@ed.gov",
    "gender": "Male",
    "ip_address": "7.144.98.16"
  }, {
    "id": 72,
    "first_name": "Darlleen",
    "last_name": "Vasilyevski",
    "email": "dvasilyevski1z@economist.com",
    "gender": "Female",
    "ip_address": "125.199.176.120"
  }, {
    "id": 73,
    "first_name": "Kiersten",
    "last_name": "Chrystal",
    "email": "kchrystal20@mashable.com",
    "gender": "Female",
    "ip_address": "244.76.250.103"
  }, {
    "id": 74,
    "first_name": "Konrad",
    "last_name": "Mangon",
    "email": "kmangon21@artisteer.com",
    "gender": "Polygender",
    "ip_address": "103.216.42.86"
  }, {
    "id": 75,
    "first_name": "Greer",
    "last_name": "Aldwick",
    "email": "galdwick22@fotki.com",
    "gender": "Agender",
    "ip_address": "102.60.89.99"
  }, {
    "id": 76,
    "first_name": "Dallis",
    "last_name": "Lunbech",
    "email": "dlunbech23@dagondesign.com",
    "gender": "Male",
    "ip_address": "207.77.62.236"
  }, {
    "id": 77,
    "first_name": "Traci",
    "last_name": "Huxstep",
    "email": "thuxstep24@g.co",
    "gender": "Genderfluid",
    "ip_address": "133.131.106.223"
  }, {
    "id": 78,
    "first_name": "Izak",
    "last_name": "Sheahan",
    "email": "isheahan25@economist.com",
    "gender": "Male",
    "ip_address": "142.145.151.194"
  }, {
    "id": 79,
    "first_name": "Erek",
    "last_name": "Durtnal",
    "email": "edurtnal26@jalbum.net",
    "gender": "Male",
    "ip_address": "243.190.132.105"
  }, {
    "id": 80,
    "first_name": "Karyl",
    "last_name": "McRannell",
    "email": "kmcrannell27@biglobe.ne.jp",
    "gender": "Female",
    "ip_address": "91.185.224.52"
  }, {
    "id": 81,
    "first_name": "Edin",
    "last_name": "Forbear",
    "email": "eforbear28@blogtalkradio.com",
    "gender": "Non-binary",
    "ip_address": "220.255.231.38"
  }, {
    "id": 82,
    "first_name": "Lorianne",
    "last_name": "Atger",
    "email": "latger29@yellowbook.com",
    "gender": "Female",
    "ip_address": "140.137.24.9"
  }, {
    "id": 83,
    "first_name": "Gasparo",
    "last_name": "Keeley",
    "email": "gkeeley2a@imdb.com",
    "gender": "Male",
    "ip_address": "206.153.229.53"
  }, {
    "id": 84,
    "first_name": "Roma",
    "last_name": "Laxen",
    "email": "rlaxen2b@irs.gov",
    "gender": "Male",
    "ip_address": "187.86.203.179"
  }, {
    "id": 85,
    "first_name": "Sayers",
    "last_name": "Larrie",
    "email": "slarrie2c@deliciousdays.com",
    "gender": "Male",
    "ip_address": "249.71.222.202"
  }, {
    "id": 86,
    "first_name": "Sergei",
    "last_name": "Vickars",
    "email": "svickars2d@ebay.co.uk",
    "gender": "Male",
    "ip_address": "178.138.215.254"
  }, {
    "id": 87,
    "first_name": "Patsy",
    "last_name": "Bison",
    "email": "pbison2e@desdev.cn",
    "gender": "Male",
    "ip_address": "104.62.106.66"
  }, {
    "id": 88,
    "first_name": "Ceciley",
    "last_name": "Bunkle",
    "email": "cbunkle2f@purevolume.com",
    "gender": "Female",
    "ip_address": "27.237.14.221"
  }, {
    "id": 89,
    "first_name": "Immanuel",
    "last_name": "Cargo",
    "email": "icargo2g@kickstarter.com",
    "gender": "Male",
    "ip_address": "58.139.158.77"
  }, {
    "id": 90,
    "first_name": "Roxana",
    "last_name": "Lempenny",
    "email": "rlempenny2h@ox.ac.uk",
    "gender": "Female",
    "ip_address": "44.201.146.86"
  }, {
    "id": 91,
    "first_name": "Alasdair",
    "last_name": "Saunders",
    "email": "asaunders2i@businessinsider.com",
    "gender": "Male",
    "ip_address": "106.120.150.198"
  }, {
    "id": 92,
    "first_name": "Mel",
    "last_name": "Reddlesden",
    "email": "mreddlesden2j@blog.com",
    "gender": "Male",
    "ip_address": "173.203.239.213"
  }, {
    "id": 93,
    "first_name": "Catarina",
    "last_name": "Nottle",
    "email": "cnottle2k@quantcast.com",
    "gender": "Female",
    "ip_address": "104.185.101.105"
  }, {
    "id": 94,
    "first_name": "Jeniece",
    "last_name": "Seres",
    "email": "jseres2l@dedecms.com",
    "gender": "Female",
    "ip_address": "13.53.79.236"
  }, {
    "id": 95,
    "first_name": "Teodor",
    "last_name": "O'Corrane",
    "email": "tocorrane2m@cdbaby.com",
    "gender": "Male",
    "ip_address": "59.248.28.237"
  }, {
    "id": 96,
    "first_name": "Johnathan",
    "last_name": "Cramp",
    "email": "jcramp2n@mail.ru",
    "gender": "Male",
    "ip_address": "253.161.225.21"
  }, {
    "id": 97,
    "first_name": "Ninon",
    "last_name": "Matusov",
    "email": "nmatusov2o@clickbank.net",
    "gender": "Female",
    "ip_address": "105.52.22.129"
  }, {
    "id": 98,
    "first_name": "Mufinella",
    "last_name": "Agiolfinger",
    "email": "magiolfinger2p@creativecommons.org",
    "gender": "Female",
    "ip_address": "25.136.213.196"
  }, {
    "id": 99,
    "first_name": "Giustino",
    "last_name": "Horrigan",
    "email": "ghorrigan2q@disqus.com",
    "gender": "Male",
    "ip_address": "161.17.130.215"
  }, {
    "id": 100,
    "first_name": "Maude",
    "last_name": "Borges",
    "email": "mborges2r@csmonitor.com",
    "gender": "Female",
    "ip_address": "189.198.34.186"
  }]

console.table(persons);
